# Generated by Django 5.0.6 on 2024-07-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='app_note_categories',
        ),
    ]
